In [2]:
data = {
    "size_m2": [45, 60, 75, 90, 110, 130],
    "bedrooms": [1, 2, 2, 3, 3, 4],
    "price": [180000, 230000, 290000, 350000, 430000, 520000]
}

df = pd.DataFrame(data)

df

   size_m2  bedrooms   price
0       45         1  180000
1       60         2  230000
2       75         2  290000
3       90         3  350000
4      110         3  430000
5      130         4  520000

In [3]:
df.shape

(6, 3)

In [4]:
df.columns

Index(['size_m2', 'bedrooms', 'price'], dtype='str')

In [5]:
df.describe()

          size_m2  bedrooms          price
count    6.000000  6.000000       6.000000
mean    85.000000  2.500000  333333.333333
std     31.622777  1.048809  126912.043032
min     45.000000  1.000000  180000.000000
25%     63.750000  2.000000  245000.000000
50%     82.500000  2.500000  320000.000000
75%    105.000000  3.000000  410000.000000
max    130.000000  4.000000  520000.000000

In [6]:
X = df[["size_m2", "bedrooms"]]
y = df["price"]

In [7]:
x

NameError: name 'x' is not defined

In [8]:
X

   size_m2  bedrooms
0       45         1
1       60         2
2       75         2
3       90         3
4      110         3
5      130         4

In [9]:
Y

NameError: name 'Y' is not defined

In [10]:
y

0    180000
1    230000
2    290000
3    350000
4    430000
5    520000
Name: price, dtype: int64